name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Debug Info
        run: |
          ls -la $GITHUB_WORKSPACE

      - name: Deploy to EC2
        env:
          SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST: ${{ secrets.HOST_DNS }}
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          echo "$SSH_KEY" > deploy_key
          chmod 600 deploy_key
          ssh -o StrictHostKeyChecking=no -i deploy_key $USERNAME@$HOST << EOF
          cd /var/www/html
          sudo rm -rf /var/www/html/*  
          sudo cp $GITHUB_WORKSPACE ./
          exit
          EOF
          rm -f deploy_key
